# Generated by Django 5.0.2 on 2024-07-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Father_name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('Aadhaar_no', models.CharField(max_length=12)),
                ('Pan_no', models.CharField(max_length=12)),
                ('Phone_no', models.CharField(max_length=10)),
            ],
        ),
    ]
