# Generated by Django 5.0.2 on 2024-07-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visiOCR_app', '0002_alter_data_aadhaar_no_alter_data_dob_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='OCR_data',
        ),
    ]
