# Generated by Django 5.0.2 on 2024-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiOCR_app', '0003_rename_data_ocr_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocr_data',
            name='Aadhaar_no',
        ),
        migrations.RemoveField(
            model_name='ocr_data',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='ocr_data',
            name='Father_name',
        ),
        migrations.RemoveField(
            model_name='ocr_data',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='ocr_data',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='ocr_data',
            name='Pan_no',
        ),
        migrations.RemoveField(
            model_name='ocr_data',
            name='Phone_no',
        ),
        migrations.AddField(
            model_name='ocr_data',
            name='id_type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocr_data',
            name='text',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
