# Generated by Django 5.0.2 on 2024-07-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiOCR_app', '0004_remove_ocr_data_aadhaar_no_remove_ocr_data_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCR_store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Aadhaar_no', models.CharField(blank=True, max_length=20, null=True)),
                ('Pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('Expiry_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
